import type { Metadata } from "next";
import Navbar from "@/components/features/Navbar";
import "./globals.css";
import Footer from "@/components/features/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="relative overflow-hidden font-inter">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
